version: 0.2

phases:
#  install:
#    runtime-versions:
#      nodejs: 12
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
#     - npm ci
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - scripts/start-service.sh
    - scripts/stop-service.sh
    - server.js
    - package.json
    - appspec.yml
    - "node_modules/**/*"
    - "views/*"
